version: '3'
services:
  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-selfsigned.crt:/etc/nginx/nginx-selfsigned.crt
      - ./nginx-selfsigned.key:/etc/nginx/nginx-selfsigned.key

  app1:
    build: .
    container_name: app1
    environment:
      - APP_NAME=App1

  app2:
    build: .
    container_name: app2
    environment:
      - APP_NAME=App2

  app3:
    build: .
    container_name: app3
    environment:
      - APP_NAME=App3
